'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class News
    Public Property Id As Integer
    Public Property Title As String
    Public Property Link As String
    Public Property Image As String
    Public Property Summary As String
    Public Property Content As String
    Public Property Tag As String
    Public Property AdDate As Date
    Public Property UdDate As Date
    Public Property IsNews As Boolean
    Public Property MenuId As Nullable(Of Integer)
    Public Property IsHomePage As Nullable(Of Boolean)

End Class
