'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property Id As Integer
    Public Property CategoryId As Integer
    Public Property MakerId As Integer
    Public Property Name As String
    Public Property Link As String
    Public Property Image As String
    Public Property Color As String
    Public Property Size As String
    Public Property OldPrice As Nullable(Of Decimal)
    Public Property NewPrice As Nullable(Of Decimal)
    Public Property Condition As String
    Public Property Origin As String
    Public Property Info As String
    Public Property AdDate As Date
    Public Property UdDate As Date
    Public Property IsHomePage As Boolean

    Public Overridable Property Maker As Maker
    Public Overridable Property Category As Category
    Public Overridable Property OrderDetails As ICollection(Of OrderDetail) = New HashSet(Of OrderDetail)

End Class
