'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq

Partial Public Class siteEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=siteEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Makers() As DbSet(Of Maker)
    Public Property Products() As DbSet(Of Product)
    Public Property Categories() As DbSet(Of Category)
    Public Property Orders() As DbSet(Of Order)
    Public Property OrderDetails() As DbSet(Of OrderDetail)
    Public Property SlideShows() As DbSet(Of SlideShow)
    Public Property Contents() As DbSet(Of Content)
    Public Property News() As DbSet(Of News)

    Public Overridable Function GetProduct(pCategory As String, pMaker As String, pProduct As String) As ObjectResult(Of GetProduct_Result)
        Dim pCategoryParameter As ObjectParameter = If(pCategory IsNot Nothing, New ObjectParameter("pCategory", pCategory), New ObjectParameter("pCategory", GetType(String)))

        Dim pMakerParameter As ObjectParameter = If(pMaker IsNot Nothing, New ObjectParameter("pMaker", pMaker), New ObjectParameter("pMaker", GetType(String)))

        Dim pProductParameter As ObjectParameter = If(pProduct IsNot Nothing, New ObjectParameter("pProduct", pProduct), New ObjectParameter("pProduct", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetProduct_Result)("GetProduct", pCategoryParameter, pMakerParameter, pProductParameter)
    End Function

    Public Overridable Function GetProductList(pCategory As String, pMaker As String, pCurrentPage As Nullable(Of Integer), pProductPerPage As Nullable(Of Integer)) As ObjectResult(Of GetProductList_Result)
        Dim pCategoryParameter As ObjectParameter = If(pCategory IsNot Nothing, New ObjectParameter("pCategory", pCategory), New ObjectParameter("pCategory", GetType(String)))

        Dim pMakerParameter As ObjectParameter = If(pMaker IsNot Nothing, New ObjectParameter("pMaker", pMaker), New ObjectParameter("pMaker", GetType(String)))

        Dim pCurrentPageParameter As ObjectParameter = If(pCurrentPage.HasValue, New ObjectParameter("pCurrentPage", pCurrentPage), New ObjectParameter("pCurrentPage", GetType(Integer)))

        Dim pProductPerPageParameter As ObjectParameter = If(pProductPerPage.HasValue, New ObjectParameter("pProductPerPage", pProductPerPage), New ObjectParameter("pProductPerPage", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetProductList_Result)("GetProductList", pCategoryParameter, pMakerParameter, pCurrentPageParameter, pProductPerPageParameter)
    End Function

    Public Overridable Function SearchProduct(pQuery As String) As ObjectResult(Of GetProductList_Result)
        Dim pQueryParameter As ObjectParameter = If(pQuery IsNot Nothing, New ObjectParameter("pQuery", pQuery), New ObjectParameter("pQuery", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetProductList_Result)("SearchProduct", pQueryParameter)
    End Function

    Public Overridable Function GetMenu() As ObjectResult(Of GetMenu_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetMenu_Result)("GetMenu")
    End Function

End Class
